# Numpy Basics

#### Step-1: Required Libraries

In [7]:
import numpy as np 
a=np.array([1,2])
print(a)

[1 2]


In [8]:
print(type(a))

<class 'numpy.ndarray'>


In [14]:
# 0-d array:
a=np.array(45)
print(a)
print(a.ndim)

45
0


## 1.creating a array():
### array(),asarray(),frombuffer(),fromiter()

In [ ]:
# 1-d array:
b=np.array([1,2,3])
print(b)
print(b.ndim)

In [18]:
# 2-d array:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.ndim)

[[1 2 3]
 [4 5 6]]
2


In [19]:
# 2-d array:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(c.ndim)

[[1 2 3]
 [4 5 6]]
2


In [20]:
# 3-d array:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)
print(d.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


### as array() with nditer():

In [25]:
a=[10,20,30,40]
b=np.asarray(a,dtype=float,order="c")
print(b)

[10. 20. 30. 40.]


In [27]:
a=(1.0,2.20,30,4.20,50)
b=np.asarray(a,dtype=int,order="f")
print(b)

[ 1  2 30  4 50]


In [35]:
a=[[20,30],[40,50]]
b=np.asarray(a,dtype=int,order="c")
print(b)

[[20 30]
 [40 50]]


In [37]:
#asarray():
a=(1,2,3,4)
b=np.asarray(a,dtype=float,order="c")
print(b)

[1. 2. 3. 4.]


In [41]:
a=[[1,2],[4,5]]
c=np.asarray(a,dtype=int,order="f")
for i in np.nditer(c):
    print(i)

1
4
2
5


### frombuffer():count(),offset()

In [43]:
#frombuffer(): a=b"satya",b is consider a frombuffer()
a=b"welcome to numpy"
b=np.frombuffer(a,dtype="S1",count=5)
print(b)

[b'w' b'e' b'l' b'c' b'o']


In [54]:
a=b"welcome to numpy in python"
s=np.frombuffer(a,dtype="S1",count=3,offset=2)
print(s)

[b'l' b'c' b'o']


In [55]:
a=b"satya gudala"
b=np.frombuffer(a,dtype="S1",count=2)
print(b)


[b's' b'a']


In [56]:
a=b"python programming language"
b=np.frombuffer(a,dtype="S1",offset=0)
print(b)

[b'p' b'y' b't' b'h' b'o' b'n' b' ' b'p' b'r' b'o' b'g' b'r' b'a' b'm'
 b'm' b'i' b'n' b'g' b' ' b'l' b'a' b'n' b'g' b'u' b'a' b'g' b'e']


### fromiter():

In [59]:
#fromiter():one type of sequence form the arrray():
a=[10,20,40,60,80]
b=np.fromiter(a,dtype=float)
print(b)

[10. 20. 40. 60. 80.]


In [60]:
a=[3.20,42.0,64.5,34,98]
b=np.fromiter(a,dtype=int,count=4)
print(b)

[ 3 42 64 34]


## 2.initializing array:

### zeros():

In [4]:
import numpy as np
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [5]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
a=np.zeros([4,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
a=np.zeros([2,3,3])
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### full():

In [12]:
np.full([2,2],2)

array([[2, 2],
       [2, 2]])

In [14]:
a=np.full([2,3,2],10)
print(a)

[[[10 10]
  [10 10]
  [10 10]]

 [[10 10]
  [10 10]
  [10 10]]]


In [16]:
s=np.full([2,3,3],2)
print(s)

[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]]


### random.rand():

In [19]:
a=np.random.rand(2,2)
print(a)

[[0.76593494 0.83984926]
 [0.85277818 0.31777184]]


In [20]:
d=np.random.rand(3,3)
print(d)

[[0.82456692 0.29735251 0.51934321]
 [0.61048758 0.98990849 0.10887897]
 [0.17607831 0.97189739 0.98289592]]


In [21]:
f=np.random.rand(2,2,2)
print(f)

[[[0.04521066 0.55600916]
  [0.35380525 0.13076594]]

 [[0.02325679 0.01634027]
  [0.77016777 0.51214908]]]


In [22]:
a=np.random.rand(1,3,4)
print(a)

[[[0.02990777 0.41978097 0.44552957 0.39147571]
  [0.38994149 0.69739931 0.15411189 0.54718068]
  [0.85845988 0.65910514 0.34208135 0.77072562]]]


### ones():

In [23]:
a=np.ones([2,2])
print(a)

[[1. 1.]
 [1. 1.]]


In [24]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [25]:
s=np.ones([3,4,5])
print(s)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


### eyes():

In [28]:
a=np.eye(2,2)
print(a)

[[1. 0.]
 [0. 1.]]


In [33]:
s=np.eye(2,2)
print(s)

[[1. 0.]
 [0. 1.]]


In [34]:
s=np.eye(4,4)
print(s)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [35]:
w=np.eye(6,6)
print(w)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### numerical range():
####   1.arange():

In [36]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [37]:
x=np.arange(10,100,10,dtype=float)
print(x)

[10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [38]:
x=np.arange(0,100,20,dtype=int)
print(x)

[ 0 20 40 60 80]


####  2.linspace(): (endpoint=,retstep=)

In [39]:
a=np.linspace(1,100,10)
print(a)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [43]:
s=np.linspace(2,100,20,endpoint=False,retstep=True)
print(s)

(array([ 2. ,  6.9, 11.8, 16.7, 21.6, 26.5, 31.4, 36.3, 41.2, 46.1, 51. ,
       55.9, 60.8, 65.7, 70.6, 75.5, 80.4, 85.3, 90.2, 95.1]), 4.9)


In [47]:
s=np.linspace(10,100,5,endpoint=True,retstep=False)
print(s)

[ 10.   32.5  55.   77.5 100. ]


In [52]:
a=np.linspace(1,100,4,endpoint=True,retstep=True,dtype=int)
print(a)

(array([  1,  34,  67, 100]), 33.0)


####   3.logspace(): base10

In [50]:
a=np.logspace(1,100,5,base=2)
print(a)

[2.00000000e+00 5.64316032e+07 1.59226292e+15 4.49269746e+22
 1.26765060e+30]


In [53]:
s=np.logspace(1,200,10,base=5)
print(s)

[5.00000000e+000 1.42552039e+016 4.06421676e+031 1.15872477e+047
 3.30357158e+062 9.41861729e+077 2.68528620e+093 7.65586045e+108
 2.18271704e+124 6.22301528e+139]


In [54]:
np.logspace(10,100,7,base=10)

array([1.e+010, 1.e+025, 1.e+040, 1.e+055, 1.e+070, 1.e+085, 1.e+100])

### array proporties:
#### 1.size():

In [55]:
import numpy as np
a=np.arange(10,100,10)
print(a)

[10 20 30 40 50 60 70 80 90]


In [57]:
a.reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [58]:
np.size(a)

9

In [61]:
v=np.full([4,4],2)
print(v)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [62]:
np.size(v)

16

In [64]:
np.size(v)

16

In [71]:
d=np.zeros([5,5])
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [72]:
np.size(d)

25

#### 2.shape():

In [73]:
np.shape(d)

(5, 5)

In [74]:
np.shape(v)

(4, 4)

In [75]:
np.shape(a)

(9,)

In [76]:
a.dtype

dtype('int32')

#### 3.dtype():

In [78]:
a=np.arange(10,100,10,dtype=float)
print(a)

[10. 20. 30. 40. 50. 60. 70. 80. 90.]


In [79]:
a.dtype

dtype('float64')

### 3. array operations():
#### 1.accessing & slicing operations:

In [81]:
#accessing the ele:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [83]:
a[0],a[1]

(array([1, 2, 3]), array([4, 5, 6]))

In [86]:
a[0][1],a[1][2]

(2, 6)

In [89]:
a=np.array([10,20,30,40,50,60,70,80,90])
print(a)

[10 20 30 40 50 60 70 80 90]


In [95]:
#slicing:
a[0:4]
a[4:9]

array([50, 60, 70, 80, 90])

In [96]:
a[5:-1]

array([60, 70, 80])

In [100]:
a[:-4]

array([10, 20, 30, 40, 50])

In [101]:
a=np.array([10,40,50,70,20])
print(a)

[10 40 50 70 20]


#### copy():

In [103]:
b=a.copy()
b

array([10, 40, 50, 70, 20])

In [110]:
b[0]=100
b

array([100,  40,  50,  70,  20])

In [111]:
c=b.view()
c

array([100,  40,  50,  70,  20])

#### viwe():

In [112]:
a,b,c

(array([10, 40, 50, 70, 20]),
 array([100,  40,  50,  70,  20]),
 array([100,  40,  50,  70,  20]))

In [114]:
a[3]=400
a

array([ 10,  40,  50, 400,  20])

In [115]:
a,b,c

(array([ 10,  40,  50, 400,  20]),
 array([100,  40,  50,  70,  20]),
 array([100,  40,  50,  70,  20]))

In [116]:
a=np.array([30,60,90,20,40,80,60,10])
print(a)
np.sort(a)

[30 60 90 20 40 80 60 10]


array([10, 20, 30, 40, 60, 60, 80, 90])

#### sort():

In [117]:
a=np.array([20,30,60,50,5])
np.sort(a)

array([ 5, 20, 30, 50, 60])

In [120]:
import numpy as np
x=np.arange(1,50,5)
print(x)

[ 1  6 11 16 21 26 31 36 41 46]


In [122]:
np.size(x)

10

In [123]:
np.shape(x)

(10,)

In [124]:
x.reshape(2,5)

array([[ 1,  6, 11, 16, 21],
       [26, 31, 36, 41, 46]])

#### reshape():

In [125]:
a=np.arange(10,210,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])

In [126]:
np.size(a)

20

In [127]:
a.reshape(5,4)

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

In [136]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

#### append():

In [137]:
b=np.array([10,20,30,40])
b

array([10, 20, 30, 40])

In [140]:
np.append(a,b)

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30, 40])

In [141]:
a=np.array([1,2,4])
b=np.array([3,5,6,7])
a,b

(array([1, 2, 4]), array([3, 5, 6, 7]))

In [142]:
np.append(a,b)

array([1, 2, 4, 3, 5, 6, 7])

In [143]:
np.insert(a,1,3)

array([1, 3, 2, 4])

#### insert():

In [144]:
np.insert(b,0,0)

array([0, 3, 5, 6, 7])

In [145]:
np.delete(a,0)

array([2, 4])

#### delete():

In [146]:
a

array([1, 2, 4])

In [147]:
b

array([3, 5, 6, 7])

In [148]:
np.delete(b,1)

array([3, 6, 7])

In [149]:
np.delete(b,2)

array([3, 5, 7])

In [150]:
a

array([1, 2, 4])

In [151]:
b

array([3, 5, 6, 7])

In [153]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

#### concatenate():

In [155]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [156]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [157]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [158]:
a

array([[1, 2],
       [3, 4]])

#### stack():

In [159]:
b

array([[5, 6],
       [7, 8]])

In [162]:
res=np.stack((a,b))
res

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [163]:
res[0]

array([[1, 2],
       [3, 4]])

In [164]:
res[1]

array([[5, 6],
       [7, 8]])

In [165]:
res[0][1]

array([3, 4])

In [166]:
res[1][1]

array([7, 8])

In [167]:
a

array([[1, 2],
       [3, 4]])

In [168]:
b

array([[5, 6],
       [7, 8]])

#### vstack():

In [171]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### hstack():

In [172]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### dstack():

In [173]:
np.dstack((a,b))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

#### split():

In [180]:
a=np.arange(10,110,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [185]:
import numpy as np
np.split(a,2)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]

In [186]:
np.split(a,5)

[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100])]

#### where():

In [187]:
a=np.arange(10,310,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260,
       270, 280, 290, 300])

In [189]:
np.size(a)

30

In [192]:
a.reshape(5,6)

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180],
       [190, 200, 210, 220, 230, 240],
       [250, 260, 270, 280, 290, 300]])

In [194]:
np.where(a==60)

(array([5], dtype=int64),)

In [195]:
a=np.arange(10,110,10)
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [196]:
a.reshape(2,5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [199]:
np.where(a%20==0)

(array([1, 3, 5, 7, 9], dtype=int64),)

#### searchsort():

In [200]:
a=np.array([10,20,30,40,50])
a

array([10, 20, 30, 40, 50])

In [206]:
np.searchsorted(a,20)

1

#### arithematic operations():
##### add(): sub(), mul(), div(), exp(), sqrt(), array eual()

In [208]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [209]:
b=np.array([[10,20,30],[40,50,60]])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [211]:
np.add(a,b)

array([[11, 22, 33],
       [44, 55, 66]])

In [212]:
np.subtract(a,b)

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [214]:
np.multiply(a,b)

array([[ 10,  40,  90],
       [160, 250, 360]])

In [220]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [221]:
np.exp(b)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26]])

In [222]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [223]:
np.sqrt(b)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669]])

In [224]:
np.array_equal(a,b)

False

### array functions():
#### sum,min,max,mean,median,var,std:

In [225]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [226]:
np.min(a)

1

In [227]:
np.max(a)

6

In [228]:
np.mean(a)

3.5

In [229]:
np.median(a)

3.5

In [230]:
np.sum(a)

21

In [231]:
np.var(a)

2.9166666666666665

In [232]:
np.std(a)

1.707825127659933

In [1]:
import numpy

In [3]:
import numpy as np

In [4]:
import numpy as np
print(np.__version__)

1.21.5


## creating the array()

In [5]:
# 0- dimentions
import numpy as np
a=np.array(10)
print(a)

10


In [6]:
import numpy as np 
x=np.array(200)
print(x)

200


In [8]:
#1 dimentions
import numpy as np
a=np.array([10,20])
print(a)

[10 20]


In [9]:
import numpy as np
c=np.array([20,30,40,50,60])
print(c)

[20 30 40 50 60]


In [11]:
# 2-dimentions
import numpy as np
a=np.array([[10,20],[30,40]])
print(a)

[[10 20]
 [30 40]]


In [13]:
import numpy as np
a=np.array([[10,20],[40,50,60]])
print(a)

[list([10, 20]) list([40, 50, 60])]


C:\Users\vamsi\AppData\Local\Temp\ipykernel_1416\1474694852.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([[10,20],[40,50,60]])


In [16]:
import numpy as np
a=np.array([[10,20],[40,50]])
print(a)
a[0][0]

[[10 20]
 [40 50]]


10

In [17]:
a[0][1]

20

In [18]:
a[1]

array([40, 50])

In [19]:
a[1][1]

50

In [20]:
# 3-d
import numpy as np
s=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(s)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [21]:
s[0]

array([[1, 2],
       [3, 4]])

In [22]:
s[1]

array([[5, 6],
       [7, 8]])

In [24]:
s[0][1]

array([3, 4])

In [25]:
s[1][1]

array([7, 8])

In [26]:
s[1][0]

array([5, 6])

In [29]:
import numpy as np
x=[1,2,3,4,5]
a=np.asarray(x,dtype='int')
print(a)

[1 2 3 4 5]


In [30]:
import numpy as np
s=[1,2,3,40,50]
d=np.asarray(s,dtype='str',order='C')
print(d)

['1' '2' '3' '40' '50']


In [32]:
import numpy as np
s=[[20,30],[40,50]]
f=np.asarray(s,dtype='int',order='F')
print(f)

[[20 30]
 [40 50]]


In [34]:
import numpy as np
d=[[10,20,30],[40,50,60]]
s=np.asarray(d,dtype='str',order='C')
print(s)

[['10' '20' '30']
 ['40' '50' '60']]


In [38]:
import numpy as np
d=[[20,40,60],[80,100,120]]
a=np.asarray(d,dtype='int',order='F')
for i in np.nditer(a):
    print(i)

20
80
40
100
60
120


In [40]:
import numpy as np
s=[10,20,30,40,50,60]
a=np.asarray(s,dtype='int',order='F')
for i in np.nditer(a):
    print(i)

10
20
30
40
50
60


#### creating frombuffer()

In [48]:
a=b'SATYA_GUDAA'
s=np.frombuffer(a,dtype='S1',count=3)
print(s)

[b'S' b'A' b'T']


In [56]:
b=b'python programming anguage'
a=np.frombuffer(b,dtype='S1',count=26)
print(a)

[b'p' b'y' b't' b'h' b'o' b'n' b' ' b'p' b'r' b'o' b'g' b'r' b'a' b'm'
 b'm' b'i' b'n' b'g' b' ' b'a' b'n' b'g' b'u' b'a' b'g' b'e']


In [57]:
d=b'satyavathi vamsikumar chinnu nanikumar'
s=np.frombuffer(d,dtype='S1',offset=4)
print(s)

[b'a' b'v' b'a' b't' b'h' b'i' b' ' b'v' b'a' b'm' b's' b'i' b'k' b'u'
 b'm' b'a' b'r' b' ' b'c' b'h' b'i' b'n' b'n' b'u' b' ' b'n' b'a' b'n'
 b'i' b'k' b'u' b'm' b'a' b'r']


In [58]:
s=b'satyavathigudaa vamsikumar gudaa'
g=np.frombuffer(s,dtype='S1',offset=4,count=15)
print(g)

[b'a' b'v' b'a' b't' b'h' b'i' b'g' b'u' b'd' b'a' b'a' b' ' b'v' b'a'
 b'm']


#### fromiter()

In [59]:
a=[10,20,30,40,50]
s=np.fromiter(a,dtype='int',count=4)
print(s)

[10 20 30 40]


In [67]:
h=['dfhiujshfee']
k=np.fromiter(h,dtype='S1')
print(k)

[b'd']


In [68]:
f=[10,30,60,90]
d=np.fromiter(f,dtype='int')
print(d)

[10 30 60 90]


## initiaizing the array()

In [73]:
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [76]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [78]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [80]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [86]:
np.full([2,3],1)

array([[1, 1, 1],
       [1, 1, 1]])

In [87]:
np.full([20],1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [88]:
np.full([10],3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [89]:
np.full(20,1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [92]:
np.full([2,3],10)

array([[10, 10, 10],
       [10, 10, 10]])

In [93]:
np.full([4,5],20)

array([[20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20]])

In [94]:
np.random.rand()

0.4242168122766624

In [95]:
np.random.rand(2)

array([0.90376692, 0.35817817])

In [97]:
np.random.rand(3)

array([0.47350124, 0.08087996, 0.59837881])

In [99]:
np.random.rand(2,3)

array([[0.63327321, 0.07433753, 0.85368591],
       [0.58711231, 0.80029446, 0.25650022]])

In [102]:
np.random.rand(4,2,2)

array([[[0.63570674, 0.55723531],
        [0.83523817, 0.06537902]],

       [[0.11462283, 0.78869839],
        [0.29908812, 0.46271208]],

       [[0.23671003, 0.0145498 ],
        [0.37090956, 0.67278767]],

       [[0.98643898, 0.61431101],
        [0.56678805, 0.02591251]]])

In [103]:
np.ones(2)

array([1., 1.])

In [105]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [109]:
np.ones([2,2,2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [111]:
np.ones([3,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [113]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [114]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [115]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [116]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [117]:
a=np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [118]:
np.arange(1,10,1)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
np.arange(1,10,2,dtype='int')

array([1, 3, 5, 7, 9])

In [120]:
np.arange(1,15,2,dtype='float')

array([ 1.,  3.,  5.,  7.,  9., 11., 13.])

In [128]:
a=np.arange(1,100,10,dtype='float')
print(a)

[ 1. 11. 21. 31. 41. 51. 61. 71. 81. 91.]


In [132]:
a=np.arange(1,11,1)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [133]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [134]:
a.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [135]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [140]:
a=np.linspace(10,100,10)
print(a)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [144]:
a=np.linspace(10,50,6,dtype='int')
print(a)

[10 18 26 34 42 50]


In [147]:
a=np.linspace(1,50,20,dtype='int',endpoint=False)
print(a)

[ 1  3  5  8 10 13 15 18 20 23 25 27 30 32 35 37 40 42 45 47]


In [149]:
a=np.linspace(10,100,5,dtype='int',endpoint=True,retstep=False)
print(a)

[ 10  32  55  77 100]


In [150]:
np.logspace(10,100,10,base=2)

array([1.02400000e+03, 1.04857600e+06, 1.07374182e+09, 1.09951163e+12,
       1.12589991e+15, 1.15292150e+18, 1.18059162e+21, 1.20892582e+24,
       1.23794004e+27, 1.26765060e+30])

In [151]:
np.logspace(10,200,20,base=10)

array([1.e+010, 1.e+020, 1.e+030, 1.e+040, 1.e+050, 1.e+060, 1.e+070,
       1.e+080, 1.e+090, 1.e+100, 1.e+110, 1.e+120, 1.e+130, 1.e+140,
       1.e+150, 1.e+160, 1.e+170, 1.e+180, 1.e+190, 1.e+200])

In [152]:
np.logspace(20,50,5,base=4)

array([1.09951163e+12, 3.60287970e+16, 1.18059162e+21, 3.86856262e+25,
       1.26765060e+30])

In [153]:
a=np.arange(10,20,1)

In [154]:
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [156]:
a.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [157]:
np.shape(a)

(10,)

In [163]:
np.shape(a)

(10,)

In [161]:
np.size(a)

10

In [166]:
a.dtype

dtype('int32')

In [167]:
a.dtype

dtype('int32')

### operations() of array

In [168]:
a=np.array([[10,20],[30,40]])
print(a)

[[10 20]
 [30 40]]


In [169]:
a[0]

array([10, 20])

In [170]:
a[1]

array([30, 40])

In [171]:
a[0][1]

20

In [172]:
a[1][1]

40

In [173]:
a=np.arange(1,10,1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [174]:
a[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [175]:
a[:3]

array([1, 2, 3])

In [176]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [177]:
a[4:]

array([5, 6, 7, 8, 9])

In [178]:
a[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [179]:
a[:3]

array([1, 2, 3])

In [180]:
a.view()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [181]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
a=np.arange(1,10,1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
a.dtype

dtype('int32')

In [197]:
a=np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [198]:
np.size(a)

4

In [199]:
np.shape(a)

(2, 2)

In [200]:
a.dtype

dtype('int32')

In [201]:
a=np.arange(1,20,2)

In [202]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [203]:
a[0]

1

In [204]:
a[7]

15

In [205]:
a[3]

7

In [206]:
a[:]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [207]:
a[:3]

array([1, 3, 5])

In [208]:
a[:6]

array([ 1,  3,  5,  7,  9, 11])

In [209]:
a[5:]

array([11, 13, 15, 17, 19])

In [212]:
b=a.copy()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [213]:
c=a.view()

In [214]:
c

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [215]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [216]:
a.reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [217]:
a.reshape(5,2)

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [218]:
a=[10,30,50,20,100,20,60,80]

In [219]:
a

[10, 30, 50, 20, 100, 20, 60, 80]

In [220]:
np.sort(a)

array([ 10,  20,  20,  30,  50,  60,  80, 100])

In [221]:
a

[10, 30, 50, 20, 100, 20, 60, 80]

In [222]:
a.append(300)

In [223]:
a

[10, 30, 50, 20, 100, 20, 60, 80, 300]

In [224]:
a.insert(1,320)

In [225]:
a

[10, 320, 30, 50, 20, 100, 20, 60, 80, 300]

In [226]:
a.remove(320)

In [227]:
a

[10, 30, 50, 20, 100, 20, 60, 80, 300]

In [228]:
a.remove(300)

In [229]:
a

[10, 30, 50, 20, 100, 20, 60, 80]

In [230]:
a.pop()

80

In [232]:
a

[10, 30, 50, 20, 100, 20, 60]

In [240]:
a=([10,20],[40,60])
b=([30,50],[80,90])
np.concatenate((a,b))

array([[10, 20],
       [40, 60],
       [30, 50],
       [80, 90]])

In [242]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [243]:
a=np.array([[100,200],[300,400]])
b=np.array([[500,600],[700,800]])
a,b

(array([[100, 200],
        [300, 400]]),
 array([[500, 600],
        [700, 800]]))

In [244]:
satya=np.stack((a,b))

In [245]:
satya

array([[[100, 200],
        [300, 400]],

       [[500, 600],
        [700, 800]]])

In [246]:
xy=np.hstack((a,b))

In [247]:
xy

array([[100, 200, 500, 600],
       [300, 400, 700, 800]])

In [248]:
xz=np.vstack((a,b))

In [249]:
xz

array([[100, 200],
       [300, 400],
       [500, 600],
       [700, 800]])

In [250]:
sad=np.dstack((a,b))

In [251]:
sad

array([[[100, 500],
        [200, 600]],

       [[300, 700],
        [400, 800]]])

In [258]:
a=np.arange(10,110,10)

In [259]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [260]:
f=np.split(a,2)

In [261]:
f

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]

In [264]:
np.split(a,5)

[array([10, 20]),
 array([30, 40]),
 array([50, 60]),
 array([70, 80]),
 array([ 90, 100])]

In [265]:
a=np.arange(10,110,10)

In [266]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [267]:
a.reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [268]:
np.where(a==20)

(array([1], dtype=int64),)

In [269]:
np.where(a==40)

(array([3], dtype=int64),)

In [270]:
np.where(a%2==0)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [271]:
np.where(a%3==0)

(array([2, 5, 8], dtype=int64),)

In [273]:
a=np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [275]:
np.searchsorted(a,20)

1

In [277]:
np.searchsorted(a,50)

4

In [278]:
np.searchsorted(a,70)

6

In [279]:
a=np.arange(10,110,10)

In [280]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [281]:
a.reshape(5,2)

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [282]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [283]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

In [284]:
np.add(b,a)

array([[ 6,  8],
       [10, 12]])

In [285]:
np.subtract(a,b)

array([[-4, -4],
       [-4, -4]])

In [288]:
np.divide(a,b)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [289]:
np.array_equal(a,b)

False

In [290]:
np.array_equal(a,b)

False

In [291]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [292]:
np.sqrt(b)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [293]:
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [295]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [296]:
np.exp(b)

array([[ 148.4131591 ,  403.42879349],
       [1096.63315843, 2980.95798704]])

In [297]:
a=np.arange(1,20,2)

In [298]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [307]:
np.max(a)

19

In [308]:
np.min(a)

1

In [309]:
np.sum (a)

100

In [310]:
np.median(a)

10.0

In [311]:
np.mean(a)

10.0

In [312]:
np.var(a)

33.0

In [313]:
np.std(a)

5.744562646538029

# series()

In [314]:
import numpy as np
a=np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [317]:
import pandas as pd
x=pd.Series(a)
x

0    10
1    20
2    30
3    40
dtype: int32

In [320]:
c=pd.Series([a])
c

0    [10, 20, 30, 40]
dtype: object

In [321]:
a=pd.Series(a)

In [322]:
a

0    10
1    20
2    30
3    40
dtype: int32

In [323]:
a=pd.Series([a])

In [324]:
a

0    0    10
1    20
2    30
3    40
dtype: int32
dtype: object

In [325]:
a=pd.Series()

C:\Users\vamsi\AppData\Local\Temp\ipykernel_1416\1633287561.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  a=pd.Series()


In [327]:
f=[1,2,3,4,5,6]
a=pd.Series(f)
a

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [336]:
f=('hga','hd','jkj','uut')
h=[1,2,3,4]
a=pd.Series(h,index=a,b,c,d)
a

SyntaxError: positional argument follows keyword argument (398122918.py, line 3)

In [337]:
a={'a':'3','b':'5','c':'4','d':'7'}
s=pd.Series(a)
s

a    3
b    5
c    4
d    7
dtype: object

In [340]:
y=[('a',10),('b',20),('c',30)]
a=pd.Series(y)

In [341]:
a

0    (a, 10)
1    (b, 20)
2    (c, 30)
dtype: object

In [342]:
a=pd.Series([10,20,30,40])
b=pd.Series([50,60,70,80])
a,b

(0    10
 1    20
 2    30
 3    40
 dtype: int64,
 0    50
 1    60
 2    70
 3    80
 dtype: int64)

In [343]:
a

0    10
1    20
2    30
3    40
dtype: int64

In [344]:
b

0    50
1    60
2    70
3    80
dtype: int64

In [345]:
a.add(b)

0     60
1     80
2    100
3    120
dtype: int64

In [346]:
a.subtract(b)

0   -40
1   -40
2   -40
3   -40
dtype: int64

In [347]:
a.divide(b)

0    0.200000
1    0.333333
2    0.428571
3    0.500000
dtype: float64

In [348]:
a.multiply(b)

0     500
1    1200
2    2100
3    3200
dtype: int64

In [351]:
a.pow(b)

0   -5376172055173529600
1                      0
2                      0
3                      0
dtype: int64

In [352]:
a.mod(b)

0    10
1    20
2    30
3    40
dtype: int64

In [353]:
a**b

0   -5376172055173529600
1                      0
2                      0
3                      0
dtype: int64

In [354]:
a/b

0    0.200000
1    0.333333
2    0.428571
3    0.500000
dtype: float64

In [355]:
a+b

0     60
1     80
2    100
3    120
dtype: int64

In [356]:
a-b

0   -40
1   -40
2   -40
3   -40
dtype: int64

In [357]:
a*b

0     500
1    1200
2    2100
3    3200
dtype: int64

In [358]:
a>b

0    False
1    False
2    False
3    False
dtype: bool

In [359]:
a<b

0    True
1    True
2    True
3    True
dtype: bool

In [360]:
a==b

0    False
1    False
2    False
3    False
dtype: bool

In [361]:
a>=b

0    False
1    False
2    False
3    False
dtype: bool

In [362]:
a<=b

0    True
1    True
2    True
3    True
dtype: bool

In [363]:
a**b

0   -5376172055173529600
1                      0
2                      0
3                      0
dtype: int64